[package]
name = "wasmtime-export-hacks"
version = "0.22.0"
authors = ["Johnnie Birch <45402135+jlb6740@users.noreply.github.com>"]
edition = "2018"

[dependencies]
wasmtime = { path = "../wasmtime", version = "0.22.0", default-features = false }