# This is a workflow triggered by PR or triggered manually
# Runs quick performance tests and reports the comparison against HEAD
# Test should take less than 10 minutes to run on current self-hosted devices
name: "Performance Testing"

# Controls when the action will run.
# This workflow runs when manually triggered using the UI or API.
on:
  pull_request_review:
    types: [submitted, edited]
  pull_request_review_comment:
    types: [created, edited]
  push:

# Env variables
env:
  SG_COMMIT: HEAD
  TOKEN: ${{ secrets.SIGHTGLASS_BENCHMARKING_TOKEN }}
  GITHUB_CONTEXT: ${{ toJson(github) }}
  GITHUB_CONTEXT_FROM_PATCH: ""

jobs:
  Wasmtime_Repo_On_PR_Comment:
    name: Benchmark x64 on PR comment Wasmtime repo
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'pull_request_review') &&
      (startsWith(github.event.review.body, '/bench_x64')) &&
      (('abrown' == github.event.review.user.login)
        || ('afonso360' == github.event.review.user.login)
        || ('akirilov-arm' == github.event.review.user.login)
        || ('alexcrichton' == github.event.review.user.login)
        || ('bbouvier' == github.event.review.user.login)
        || ('bjorn3' == github.event.review.user.login)
        || ('cfallin' == github.event.review.user.login)
        || ('fitzgen' == github.event.review.user.login)
        || ('jlb6740' == github.event.review.user.login)
        || ('sparker-arm' == github.event.review.user.login)
        || ('uweigand' == github.event.review.user.login))
    steps:
      - run: echo "MESSAGE=Requested from pull request comment." >> $GITHUB_ENV
      - run: echo "ACTOR=${{ github.event.review.user.login }}" >> $GITHUB_ENV
      - run: echo "REPOSITORY=${{ github.repository }}" >> $GITHUB_ENV
      - run: echo "REFS=${{ github.ref }}" >> $GITHUB_ENV
      - run: echo "PR_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV
      - run: echo "PUBLISH=true" >> $GITHUB_ENV
      - run: echo "$GITHUB_CONTEXT"
      - run: echo "$GITHUB_ENV"
      - run: |
          # Create and Push Branch
          git clone https://jlb6740:${{env.TOKEN}}@github.com/bytecodealliance/wasmtime-sightglass-benchmarking.git
          cd wasmtime-sightglass-benchmarking
          git remote add wasmtime ${{ github.event.repository.clone_url }}
          git fetch wasmtime refs/pull/*/merge:refs/remotes/wasmtime/pull/*/merge
          git checkout wasmtime/pull/${{ github.ref_name }} -b ${{ github.ref_name }}
          git submodule update --init --recursive
          git checkout -b wasmtime-performance-testing/${{ github.ref }}/${{ github.sha }}
          sudo apt install jq
          export commit_url=${{ github.event.pull_request._links.commits.href }}
          echo $commit_url
          echo $(curl -sSL $commit_url | jq -r '.[].commit.committer.name' | tail -n 1)
          echo $(curl -sSL $commit_url | jq -r '.[].commit.committer.email' | tail -n 1)
          git config user.name $(curl -sSL $commit_url | jq -r '.[].commit.committer.name' | tail -n 1)
          git config user.email $(curl -sSL $commit_url | jq -r '.[].commit.committer.email' | tail -n 1)
          git commit --allow-empty -m "${{ github.event.pull_request._links.comments.href }}"
          git push origin wasmtime-performance-testing/${{ github.ref }}/${{ github.sha }}
          #curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ env.TOKEN }}" https://api.github.com/repos/bytecodealliance/wasmtime-sightglass-benchmarking/dispatches -d '{"event_type":"Performance Testing", "client_payload":{"message":"${{ env.MESSAGE }}", "actor":"${{ env.ACTOR }}", "repository":"${{ env.REPOSITORY }}", "ref":"${{ env.REFS }}", "pr_number":"${{ env.PR_NUMBER }}", "publish":"${{ env.PUBLISH }}" }'

  Performance_Repo_On_Push:
    name: Benchmark x64 on push Performance repo
    runs-on: [self-hosted, linux, x64]
    if: (github.event_name == 'push') && (github.repository == 'bytecodealliance/wasmtime-sightglass-benchmarking')
    steps:
      - run: echo "$GITHUB_CONTEXT"
      - run: echo "${{ github.event.head_commit.message }}"
      - name: "Build sightglass commit '${{ env.SG_COMMIT }}'"
        run: |
          cd ../ && ls -l && rm -rf ./sightglass
          git clone https://github.com/bytecodealliance/sightglass.git && cd ./sightglass
          git checkout ${{env.SG_COMMIT}}
          cargo build --release

      - name: Checkout ${{ env.event.ref_name }}
        uses: actions/checkout@v3
        with:
          submodules: true
          repository: ${{ env.repository }}
          ref: ${{ env.event.ref_name }}
          path: wasmtime_commit


#      - name: Build ${{ env.REF }} from ${{ env.REPOSITORY }}
#        working-directory: ./wasmtime_commit
#          cargo build --release -p wasmtime-bench-api
#          cp target/release/libwasmtime_bench_api.so /tmp/wasmtime_commit.so

          #echo "${{fromJson(GITHUB_CONTEXT_PERFORMANCE).ref}}"
          #echo "${{fromJson(steps.set_var.outputs.packageJson).version}}"


#      - name: Checkout main from bytecodealliance/wasmtime
#        uses: actions/checkout@v3
#        with:
#          ref: 'main'
#          repository: 'bytecodealliance/wasmtime'
#          submodules: true
#          path: wasmtime_main

#      - name: Build main from bytecodealliance/wasmtime
#        working-directory: ./wasmtime_main
#        run: |
#          cargo build --release -p wasmtime-bench-api
#          cp target/release/libwasmtime_bench_api.so /tmp/wasmtime_main.so
