name: "SG Benchmarking"

# Controls when the action will run.
# This workflow runs when manually triggered using the UI or API or PR comment.
on:
  issue_comment:
    types: [created, edited]
  pull_request_review_comment:
    types: [created, edited]
 # push:
  workflow_dispatch:
      inputs:
        actor:
          type: string
          required: false
        pr_number:
          type: string
          required: false
          default: ""
        post_results:
          type: boolean
          required: false
          default: false
        repository:
          description: 'Repository for the commit'
          type: string
          default: 'jlb6740/wasmtime'
          required: true
        ref:
          description: 'Ref for the commit'
          type: string
          default: 'refs/heads/main'
          required: true
        sg_commit:
          description: 'Sightglass ref'
          type: string
          default: '81c425a'
          required: false
        message:
          type: string
          default: 'Triggered by Wasmtime workflow dispatch'
          required: false

# Env variables
env:
  SG_COMMIT: 649509c
  TOKEN: ${{ secrets.SIGHTGLASS_BENCHMARKING_TOKEN }}
  USER: jlb6740
  GITHUB_CONTEXT: ${{ toJson(github) }}

jobs:
  Performance_x86-64:
    #if: >-
    #  ${{
    #    github.event.issue.pull_request
    #    && contains(github.event.comment.body, '/bench_x64')
    #    && (('abrown' == github.event.comment.user.login)
    #    || ('akirilov-arm' == github.event.comment.user.login)
    #    || ('bbouvier' == github.event.comment.user.login)
    #    || ('bjorn3' == github.event.comment.user.login)
    #    || ('cfallin' == github.event.comment.user.login)
    #    || ('fitzgen' == github.event.comment.user.login)
    #    || ('jlb6740' == github.event.comment.user.login))
    #  }}

  #steps:
  #    if: ${{ github.event_name == 'workflow_dispatch' }}
  #    name: Set variables
  #    run: |
  #      echo "MESSAGE=${{ github.event.inputs.message }}" >> $GITHUB_ENV

    name: Performance x86-64
    runs-on: ubuntu-latest
    steps:
      - run: echo "$GITHUB_CONTEXT"

      - name: Set Variables
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "MESSAGE=${{ github.event.inputs.message }}" >> $GITHUB_ENV


      - run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ env.TOKEN }}" \
          https://api.github.com/repos/bytecodealliance/wasmtime-sightglass-benchmarking/dispatches \
          -d '{"event_type":"bench-sightglass", "client_payload":{"message":"${{ env.MESSAGE }}", "actor":"jlb6740", "repository":"jlb6740/wasmtime", "ref":"refs/heads/add-sg-benchmarking-workflow", "pr_number":"4", "publish":"true" }}'